# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '6.x'
    displayName: 'install node.js'

  - script: |
      npm install
    displayName: 'npm install and test'
  
  - script: |
      wget https://github.com/github/codeql-action/releases/download/codeql-bundle-20200826/codeql-runner-linux
      chmod +x codeql-runner-linux
    displayName: 'get codeql package and install agent'

  - script: |
      ./codeql-runner-linux \
      --repository Marimuthukumaran/node-application-CodeQL \
      --github-url https://github.com \
      --github-auth $(GITHUB_PAT) \
      --config-file ./github/codeql/codeql-config.yml
    displayName: 'initialize codeql executable and codeql database' 
  
  - script: |
      ./codeql-runner-linux \
      --repository Marimuthukumaran/node-application-CodeQL \
      --github-url https://github.com \
      --github-auth $(GITHUB_PAT) \
      --commit $(Build.SourceVersion) \
      --ref $(Build.SourceBranch)
    displayName: 'Populate the codeql runner database analyse them and upload to github'
  

